VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFireFlakeLayout"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Sub connectWithIterationBox(ByRef box As FireFlakePMCollection)
End Sub

Public Sub endingBalanceBackgroundColor()
End Sub

Public Sub init(lt As LAYOUT_TYPE, st As START_TYPE)

End Sub

Public Sub buildLayoutForCommonData()

End Sub

Public Sub buildIterationLayoutForCommonData(ByRef ic As Collection, ByRef mcd As CommonData, ByRef notYetReceivedWithPastEdaCollection As Collection)

End Sub

Public Sub buildLayoutForDatesLabels(ByRef c As Collection)

End Sub

Public Sub buildLayoutTheThinLines(ByRef c As Collection)
End Sub

Public Sub closingDayLines()

End Sub

Public Sub finalAdjustOnColumnsWidth()

End Sub

Public Sub shrinkColumnsWidthForRqmItEbal()

End Sub

Public Sub autoFitContent()

End Sub

Public Sub addFilterOnListLayout()

End Sub

Public Sub freezePanesAtTheEnd(ByRef lt As LAYOUT_TYPE)

End Sub

Public Sub buildIterationLayoutForCoverage(ByRef ic As Collection, ByRef mcd As CommonData)

End Sub
