VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IReport"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Sub repRun(imgo As MGO, sh As StatusHandler)

End Sub

Public Sub repInit(zakres As Range, limit As Date, lt As LAYOUT_TYPE, st As START_TYPE, rqm_limit As Date, Optional mrowFlag As Long)

End Sub

Public Sub pause()

End Sub

Public Sub clearAndStop()

End Sub

Public Sub fullyRefresh()

End Sub

Public Sub partialyRefresh()

End Sub


Public Sub setCollectionOfIterations(coi As Collection)

End Sub

Public Function getCollectionOfIterations() As Collection

End Function

Public Sub fakeDataChangeToRecalcFirstRunoutFormula()

End Sub

Public Sub adjustLayoutAfterAllJobs()

End Sub


