VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITransit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Property Get mNotYetReceived() As Boolean
End Property

Property Let mNotYetReceived(arg As Boolean)
End Property

Property Get mOnPo400() As Boolean
End Property

Property Let mOnPo400(arg As Boolean)
End Property

Property Get mQty() As Long
End Property

Property Let mQty(arg As Long)
End Property

Property Get mPickupDate() As Date
End Property

Property Let mPickupDate(arg As Date)
End Property

Property Get mPickupTime() As Date
End Property

Property Let mPickupTime(arg As Date)
End Property

Property Get mDeliveryDate() As Date
End Property

Property Let mDeliveryDate(arg As Date)
End Property

Property Get mDeliveryTime() As Date
End Property

Property Let mDeliveryTime(arg As Date)
End Property


' SID
Property Get mName() As String
End Property

Property Let mName(arg As String)
End Property

Property Get mRoute() As String
End Property

Property Let mRoute(arg As String)
End Property

Property Get mTRLR() As String
End Property

Property Let mTRLR(arg As String)
End Property

Property Get mst() As String
End Property

Property Let mst(arg As String)
End Property






